name: Terraform Pip
on: push
env:
    AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
    AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

jobs:
    terraform_pip:
        name: Terraform Pipeline
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
        steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Terraform Pipeline
          run: |
            terraform init
            terraform validate
            terraform plan